### ISSUE TITLE
export でエラー、go-e-mon サーバからステータス 400 が返ってきました

### ISSUE THREAD

**Issue by HanaiHirofumi** [goemon-cloud/goemon-cli#3]
@yacchin1205
goemon export AYrvKOTQO6fV2aN1e2OI --all --dry-run
が成功したため
goemon export AYrvKOTQO6fV2aN1e2OI --all
を実行したところエラーとなりました。

Traceback (most recent call last):
  File "c:\users\hanai\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
    exec(code, run_globals)
  File "C:\Users\hanai\anaconda3\Scripts\goemon.exe\__main__.py", line 7, in <module>
  File "c:\users\hanai\anaconda3\lib\site-packages\goemon\cli.py", line 261, in main
    flush_export(args, api, task)
  File "c:\users\hanai\anaconda3\lib\site-packages\goemon\cli.py", line 234, in flush_export
    api.patch_task(args.target_id[-1], task, shared=args.shared)
  File "c:\users\hanai\anaconda3\lib\site-packages\goemon\api.py", line 275, in patch_task
    return self._patch('tasks' if not shared else 'shares', task_id, data, data_files)
  File "c:\users\hanai\anaconda3\lib\site-packages\goemon\api.py", line 297, in _patch
    resp.raise_for_status()
  File "c:\users\hanai\anaconda3\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://goemon.cloud/api/v1/tasks/AYrvKOTQO6fV2aN1e2OI

その後、import も失敗します。
よろしくお願いいたします。

**Comment by HanaiHirofumi** [comment]
上記エラー後、確認してみると
ファイルの一覧と実体の URL が食い違った状態になってしまったようです。

**Comment by yacchin1205** [comment]
お手数をおかけしております。

> ファイルの一覧と実体の URL が食い違った

この辺を、もう少し詳しく、(Private Projectの方でIssueを立ててください。こちらはPublicのため...)教えてもらえるとありがたいです。
