### ISSUE TITLE
exportに失敗することがあり、一度失敗すると、二度と成功しなくなる

### ISSUE THREAD

**Issue by exKAZUu** [goemon-cloud/goemon-cli#4]
現在、 `goemon export 7IhO24ybgQoTg9J8iRf8 --all` が成功しなくなってしまっています。exportするファイルは特に変えたりしていないです。（過去に成功していたファイルを使用しています。）

```
Traceback (most recent call last):
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/bin/goemon", line 8, in <module>
    sys.exit(main())
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/goemon/cli.py", line 247, in main
    task = api.get_task(args.target_id[-1], shared=args.shared)
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/goemon/api.py", line 265, in get_task
    return self._get('tasks' if not shared else 'shares', task_id)
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/goemon/api.py", line 286, in _get
    return Task(respjson['data']['attributes'])
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/goemon/api.py", line 31, in __init__
    self._download_files()
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/goemon/api.py", line 180, in _download_files
    r.raise_for_status()
  File "/Users/exkazuu/.asdf/installs/python/3.9.13/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://goemon.cloud/api/v1/users/Uu0uRIh3pwhIRCiZntszzpdWSmn2/tasks/F4GzSUxOq9TpAc2tGaXi/files/8SlgvBUcW7HsafUn5bJi
```

**Comment by exKAZUu** [comment]
以下のタスクで問題が起こっています。

公開用: https://goemon.cloud/t/7IhO24ybgQoTg9J8iRf8
管理用: https://goemon.cloud/s/TW8wZy01Ca2WDIU8oWcJ

**Comment by yacchin1205** [comment]
@exKAZUu 原因は不明ですが、firestoreとstorageの間で矛盾が起きているようです(firestoreにレコードはあるが、storageから消えている)。お手数ですが、Web UIのタスク編集画面のファイルタブで、一旦ファイルを全て削除して、試してみていただけますか。（この時もエラーが発生すると思いますが、firestoreの方が消えて、問題が解消する可能性があります。）
お手数をおかけします。

**Comment by exKAZUu** [comment]
@yacchin1205 すみません、記載していなかったのですが、ファイルを削除しても状況が変わりません。ファイルを削除して、さらに、ファイルをアップロードしてデプロイすると、再度 import / export できるようにはなります。なお、この症状は比較的短期間で2回起こっています。

**Comment by exKAZUu** [comment]
いったん、開発の都合で、ファイルをアップロードして使える状態に戻します。

**Comment by yacchin1205** [comment]
@exKAZUu 承知です。原因を調査します。問題が発生したら、お手数ですが再度Web UIの方からお願いします。

**Comment by exKAZUu** [comment]
本日、かなり使わせていただいているのですが、全く失敗せず再現できなくなりました・・。もしかすると、ネットワーク環境などの問題だったのかもしれないです。来週もう少し様子を見て、再現しなかったら閉じようと思います。

**Comment by yacchin1205** [comment]
@exKAZUu なるほど、了解です。問題が発生する契機となったエラーはいくつか特定できているので、引き続き調査します。よろしくおねがいいたします。
